/* Generated by MyraPad at 13/11/2020 18:43:16 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace Rivière.Screen.UI
{
	partial class GameFinishedDialog: Dialog
	{
		private void BuildUI()
		{
			keepplayers_checkbox = new CheckBox();
			keepplayers_checkbox.Text = "Conserver les joueurs";
			keepplayers_checkbox.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans24.fnt");
			keepplayers_checkbox.ImageTextSpacing = 10;
			keepplayers_checkbox.Padding = new Thickness(5, 0);
			keepplayers_checkbox.Id = "keepplayers_checkbox";
			
			Title = "Partie terminee";
			Left = 483;
			Top = 228;
			Padding = new Thickness(10);
			Content = keepplayers_checkbox;
		}

		
		public CheckBox keepplayers_checkbox;
	}
}