/* Generated by MyraPad at 13/11/2020 16:55:52 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace Rivière.Screen.UI
{
	partial class GiveSipsDialog: Dialog
	{
		private void BuildUI()
		{
			
			Title = "";
			Content = null;
			Left = 554;
			Top = 254;
		}

		
	}
}