/* Generated by MyraPad at 13/11/2020 18:07:27 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace Rivière.Screen.UI
{
	partial class IngameScreenUI: VerticalSplitPane
	{
		private void BuildUI()
		{
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/background.jpg");

			drawpile_image = new Image();
			drawpile_image.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/cards/back.png");
			drawpile_image.Margin = new Thickness(15);
			drawpile_image.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			drawpile_image.Id = "drawpile_image";

			currentcard_image = new Image();
			currentcard_image.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/cards/two_heart.png");
			currentcard_image.Margin = new Thickness(15);
			currentcard_image.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			currentcard_image.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			currentcard_image.Id = "currentcard_image";

			remainingcardnumber_label = new Label();
			remainingcardnumber_label.Text = "X cartes restantes";
			remainingcardnumber_label.Padding = new Thickness(5);
			remainingcardnumber_label.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			remainingcardnumber_label.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			remainingcardnumber_label.Background = new SolidBrush("#404040FF");
			remainingcardnumber_label.Id = "remainingcardnumber_label";

			var panel1 = new Panel();
			panel1.MaxWidth = 0;
			panel1.Widgets.Add(image1);
			panel1.Widgets.Add(drawpile_image);
			panel1.Widgets.Add(currentcard_image);
			panel1.Widgets.Add(remainingcardnumber_label);

			roundname_label = new Label();
			roundname_label.Text = "----- Couleur -----";
			roundname_label.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans48.fnt");
			roundname_label.TextColor = Color.Black;
			roundname_label.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			roundname_label.Id = "roundname_label";

			rounddesc_label = new Label();
			rounddesc_label.Text = "La prochaine carte est-elle plus grande ou plus petite que ta precedente ?";
			rounddesc_label.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			rounddesc_label.Wrap = true;
			rounddesc_label.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			rounddesc_label.TextColor = Color.Black;
			rounddesc_label.Top = 50;
			rounddesc_label.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			rounddesc_label.Id = "rounddesc_label";

			var label1 = new Label();
			label1.Text = "A ton tour";
			label1.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			label1.TextColor = Color.Black;
			label1.Top = -30;
			label1.Padding = new Thickness(0, 0, 0, 5);
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			currentplayername_label = new Label();
			currentplayername_label.Text = "Guillaume";
			currentplayername_label.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans48.fnt");
			currentplayername_label.TextColor = Color.Black;
			currentplayername_label.Top = -30;
			currentplayername_label.Padding = new Thickness(10, 0, 0, 0);
			currentplayername_label.Id = "currentplayername_label";

			playerturn_panel = new HorizontalStackPanel();
			playerturn_panel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			playerturn_panel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			playerturn_panel.Padding = new Thickness(0, 0, 0, 20);
			playerturn_panel.Id = "playerturn_panel";
			playerturn_panel.Widgets.Add(label1);
			playerturn_panel.Widgets.Add(currentplayername_label);

			roundchoice_combobox = new ComboBox();
			roundchoice_combobox.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			roundchoice_combobox.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			roundchoice_combobox.Id = "roundchoice_combobox";

			drawcard_button = new TextButton();
			drawcard_button.Text = "Piocher une carte";
			drawcard_button.Top = -30;
			drawcard_button.Padding = new Thickness(5);
			drawcard_button.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			drawcard_button.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			drawcard_button.Id = "drawcard_button";

			var panel2 = new Panel();
			panel2.Margin = new Thickness(15);
			panel2.Widgets.Add(roundname_label);
			panel2.Widgets.Add(rounddesc_label);
			panel2.Widgets.Add(playerturn_panel);
			panel2.Widgets.Add(roundchoice_combobox);
			panel2.Widgets.Add(drawcard_button);

			var panel3 = new Panel();
			panel3.Background = new SolidBrush("#FFE2BDFF");
			panel3.Widgets.Add(panel2);

			var horizontalSplitPane1 = new HorizontalSplitPane();
			horizontalSplitPane1.Widgets.Add(panel1);
			horizontalSplitPane1.Widgets.Add(panel3);

			
			Widgets.Add(horizontalSplitPane1);
		}

		
		public Image drawpile_image;
		public Image currentcard_image;
		public Label remainingcardnumber_label;
		public Label roundname_label;
		public Label rounddesc_label;
		public Label currentplayername_label;
		public HorizontalStackPanel playerturn_panel;
		public ComboBox roundchoice_combobox;
		public TextButton drawcard_button;
	}
}