/* Generated by MyraPad at 06/11/2020 18:57:04 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace Rivière.Screen.UI
{
	partial class LobbyScreenUI: Panel
	{
		private void BuildUI()
		{
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/splash_screen_bg.jpg");

			var label1 = new Label();
			label1.Text = "RIVIERE";
			label1.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans48.fnt");
			label1.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label1.TextColor = Color.Black;
			label1.Top = 30;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label2 = new Label();
			label2.Text = "Ajouter un joueur";
			label2.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			label2.TextColor = Color.Black;
			label2.Left = 30;
			label2.Top = 100;

			var textBox1 = new TextBox();
			textBox1.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			textBox1.Left = 30;
			textBox1.Top = 150;
			textBox1.Width = 250;
			textBox1.Padding = new Thickness(3);

			var textButton1 = new TextButton();
			textButton1.Text = "OK";
			textButton1.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			textButton1.Enabled = false;
			textButton1.Left = 280;
			textButton1.Top = 150;
			textButton1.Padding = new Thickness(3);

			var imageButton1 = new ImageButton("transparent-bg");
			imageButton1.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/remove-icon.png");
			imageButton1.OverImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/remove-icon-dark.png");
			imageButton1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			imageButton1.GridColumn = 1;
			imageButton1.GridRow = 1;

			var label3 = new Label();
			label3.Text = "Georges";
			label3.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			label3.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label3.TextColor = Color.Black;
			label3.Padding = new Thickness(3);
			label3.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label3.GridColumn = 2;
			label3.GridRow = 1;

			var grid1 = new Grid();
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.Left = 30;
			grid1.Top = 200;
			grid1.Widgets.Add(imageButton1);
			grid1.Widgets.Add(label3);

			var textButton2 = new TextButton("transparent-bg");
			textButton2.Text = "Start the game";
			textButton2.TextColor = Color.Black;
			textButton2.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans48.fnt");
			textButton2.Left = 100;
			textButton2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textButton2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			
			Widgets.Add(image1);
			Widgets.Add(label1);
			Widgets.Add(label2);
			Widgets.Add(textBox1);
			Widgets.Add(textButton1);
			Widgets.Add(grid1);
			Widgets.Add(textButton2);
		}

		
	}
}