/* Generated by MyraPad at 13/11/2020 16:07:08 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace Rivière.Screen.UI
{
	partial class LobbyScreenUI: Panel
	{
		private void BuildUI()
		{
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/background.jpg");

			var label1 = new Label();
			label1.Text = "RIVIERE";
			label1.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans48.fnt");
			label1.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label1.Top = 30;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label2 = new Label();
			label2.Text = "Ajouter un joueur";
			label2.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			label2.Left = 30;
			label2.Top = 100;

			playername_textbox = new TextBox();
			playername_textbox.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			playername_textbox.Left = 30;
			playername_textbox.Top = 150;
			playername_textbox.Width = 250;
			playername_textbox.Padding = new Thickness(3);
			playername_textbox.Id = "playername_textbox";

			add_player_button = new TextButton();
			add_player_button.Text = "OK";
			add_player_button.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			add_player_button.Enabled = false;
			add_player_button.Left = 280;
			add_player_button.Top = 150;
			add_player_button.Padding = new Thickness(3);
			add_player_button.Id = "add_player_button";

			removeplayer_button = new ImageButton();
			removeplayer_button.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/remove-icon.png");
			removeplayer_button.OverImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/remove-icon-dark.png");
			removeplayer_button.Visible = false;
			removeplayer_button.BorderThickness = new Thickness(0, 7, 0, 0);
			removeplayer_button.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			removeplayer_button.Id = "removeplayer_button";

			playername_label = new Label();
			playername_label.Text = "Georges";
			playername_label.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			playername_label.Padding = new Thickness(3);
			playername_label.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			playername_label.GridColumn = 1;
			playername_label.Visible = false;
			playername_label.Id = "playername_label";

			playerslist_grid = new Grid();
			playerslist_grid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			playerslist_grid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			playerslist_grid.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			playerslist_grid.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			playerslist_grid.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			playerslist_grid.Left = 30;
			playerslist_grid.Top = 200;
			playerslist_grid.Id = "playerslist_grid";
			playerslist_grid.Widgets.Add(removeplayer_button);
			playerslist_grid.Widgets.Add(playername_label);

			startgame_button = new TextButton("transparent-bg");
			startgame_button.Text = "Demarrez le jeu";
			startgame_button.TextColor = new Color
			{
				B = 255,
				G = 254,
				R = 255,
				A = 255,
			};
			startgame_button.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans48.fnt");
			startgame_button.Visible = false;
			startgame_button.Left = 100;
			startgame_button.Top = 150;
			startgame_button.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			startgame_button.Id = "startgame_button";

			messagestartgame_label = new Label();
			messagestartgame_label.Text = "Il faut encore X joueurs";
			messagestartgame_label.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans32.fnt");
			messagestartgame_label.Left = 100;
			messagestartgame_label.Top = 150;
			messagestartgame_label.Padding = new Thickness(15, 5, 0, 0);
			messagestartgame_label.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			messagestartgame_label.Id = "messagestartgame_label";

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/background_rules.png");
			image2.MaxWidth = 400;
			image2.MaxHeight = 350;

			var label3 = new Label();
			label3.Text = "Regles Speciales";
			label3.TextColor = Color.Black;
			label3.Top = 65;
			label3.BorderThickness = new Thickness(0, 0, 0, 3);
			label3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label3.Border = new SolidBrush("#000000FF");

			ruleshuffleplayer_checkbox = new CheckBox();
			ruleshuffleplayer_checkbox.Text = "Ordre des joueurs aleatoire";
			ruleshuffleplayer_checkbox.TextColor = Color.Black;
			ruleshuffleplayer_checkbox.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans24.fnt");
			ruleshuffleplayer_checkbox.ImageTextSpacing = 15;
			ruleshuffleplayer_checkbox.Left = 50;
			ruleshuffleplayer_checkbox.Top = 80;
			ruleshuffleplayer_checkbox.Id = "ruleshuffleplayer_checkbox";

			ruleguillaumeheart_checkbox = new CheckBox();
			ruleguillaumeheart_checkbox.Text = "Le Coeur de Guilllaume";
			ruleguillaumeheart_checkbox.TextColor = Color.Black;
			ruleguillaumeheart_checkbox.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans24.fnt");
			ruleguillaumeheart_checkbox.ImageTextSpacing = 15;
			ruleguillaumeheart_checkbox.Left = 50;
			ruleguillaumeheart_checkbox.Top = 80;
			ruleguillaumeheart_checkbox.GridRow = 1;
			ruleguillaumeheart_checkbox.Id = "ruleguillaumeheart_checkbox";

			ruleaceworst_checkbox = new CheckBox();
			ruleaceworst_checkbox.Text = "Le 1 (as), c\'est moins bien";
			ruleaceworst_checkbox.TextColor = Color.Black;
			ruleaceworst_checkbox.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans24.fnt");
			ruleaceworst_checkbox.ImageTextSpacing = 15;
			ruleaceworst_checkbox.Left = 50;
			ruleaceworst_checkbox.Top = 80;
			ruleaceworst_checkbox.GridRow = 2;
			ruleaceworst_checkbox.Id = "ruleaceworst_checkbox";

			rulejuliencheh_checkbox = new CheckBox();
			rulejuliencheh_checkbox.Text = "On est bien cheh Julien (a venir)";
			rulejuliencheh_checkbox.TextColor = Color.Black;
			rulejuliencheh_checkbox.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans24.fnt");
			rulejuliencheh_checkbox.ImageTextSpacing = 15;
			rulejuliencheh_checkbox.Left = 50;
			rulejuliencheh_checkbox.Top = 80;
			rulejuliencheh_checkbox.GridRow = 3;
			rulejuliencheh_checkbox.IsDraggable = true;
			rulejuliencheh_checkbox.Id = "rulejuliencheh_checkbox";

			ruleericsubtitles_checkbox = new CheckBox();
			ruleericsubtitles_checkbox.Text = "Sous-titrages teletextes (a venir)";
			ruleericsubtitles_checkbox.TextColor = Color.Black;
			ruleericsubtitles_checkbox.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans24.fnt");
			ruleericsubtitles_checkbox.ImageTextSpacing = 15;
			ruleericsubtitles_checkbox.Enabled = false;
			ruleericsubtitles_checkbox.Left = 50;
			ruleericsubtitles_checkbox.Top = 80;
			ruleericsubtitles_checkbox.GridRow = 4;
			ruleericsubtitles_checkbox.IsDraggable = true;
			ruleericsubtitles_checkbox.Id = "ruleericsubtitles_checkbox";

			var grid1 = new Grid();
			grid1.RowSpacing = 5;
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.Top = 40;
			grid1.Widgets.Add(ruleshuffleplayer_checkbox);
			grid1.Widgets.Add(ruleguillaumeheart_checkbox);
			grid1.Widgets.Add(ruleaceworst_checkbox);
			grid1.Widgets.Add(rulejuliencheh_checkbox);
			grid1.Widgets.Add(ruleericsubtitles_checkbox);

			var panel1 = new Panel();
			panel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			panel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			panel1.Left = 150;
			panel1.Top = 100;
			panel1.Widgets.Add(image2);
			panel1.Widgets.Add(label3);
			panel1.Widgets.Add(grid1);

			
			Widgets.Add(image1);
			Widgets.Add(label1);
			Widgets.Add(label2);
			Widgets.Add(playername_textbox);
			Widgets.Add(add_player_button);
			Widgets.Add(playerslist_grid);
			Widgets.Add(startgame_button);
			Widgets.Add(messagestartgame_label);
			Widgets.Add(panel1);
		}

		
		public TextBox playername_textbox;
		public TextButton add_player_button;
		public ImageButton removeplayer_button;
		public Label playername_label;
		public Grid playerslist_grid;
		public TextButton startgame_button;
		public Label messagestartgame_label;
		public CheckBox ruleshuffleplayer_checkbox;
		public CheckBox ruleguillaumeheart_checkbox;
		public CheckBox ruleaceworst_checkbox;
		public CheckBox rulejuliencheh_checkbox;
		public CheckBox ruleericsubtitles_checkbox;
	}
}