/* Generated by MyraPad at 13/11/2020 18:05:53 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace Rivière.Screen
{
	partial class ScoreGrid: Grid
	{
		private void BuildUI()
		{
			gridcontent_label = new Label();
			gridcontent_label.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			gridcontent_label.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			gridcontent_label.Padding = new Thickness(5, 0);
			gridcontent_label.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			gridcontent_label.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			gridcontent_label.Visible = false;
			gridcontent_label.Id = "gridcontent_label";

			gridfirstcolumn_label = new Label();
			gridfirstcolumn_label.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			gridfirstcolumn_label.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			gridfirstcolumn_label.TextColor = Color.Black;
			gridfirstcolumn_label.Padding = new Thickness(5, 0);
			gridfirstcolumn_label.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			gridfirstcolumn_label.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			gridfirstcolumn_label.Visible = false;
			gridfirstcolumn_label.Background = new SolidBrush("#FFFFFFFF");
			gridfirstcolumn_label.Id = "gridfirstcolumn_label";

			gridfirstrowmovablecolumns_label = new Label();
			gridfirstrowmovablecolumns_label.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			gridfirstrowmovablecolumns_label.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			gridfirstrowmovablecolumns_label.TextColor = Color.Black;
			gridfirstrowmovablecolumns_label.BorderThickness = new Thickness(0, 0, 0, 1);
			gridfirstrowmovablecolumns_label.Padding = new Thickness(5, 0);
			gridfirstrowmovablecolumns_label.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			gridfirstrowmovablecolumns_label.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			gridfirstrowmovablecolumns_label.Visible = false;
			gridfirstrowmovablecolumns_label.Background = new SolidBrush("#FFFFFFFF");
			gridfirstrowmovablecolumns_label.Border = new SolidBrush("#000000FF");
			gridfirstrowmovablecolumns_label.Id = "gridfirstrowmovablecolumns_label";

			graycell_label = new Label();
			graycell_label.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			graycell_label.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			graycell_label.Visible = false;
			graycell_label.Background = new SolidBrush("#404040FF");
			graycell_label.Id = "graycell_label";

			var label1 = new Label();
			label1.Text = "Joueurs";
			label1.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label1.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label1.TextColor = Color.Black;
			label1.BorderThickness = new Thickness(0, 0, 0, 1);
			label1.Padding = new Thickness(5, 0);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label1.Border = new SolidBrush("#000000FF");

			var label2 = new Label();
			label2.Text = "Couleur";
			label2.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label2.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label2.TextColor = Color.Black;
			label2.BorderThickness = new Thickness(0, 0, 0, 1);
			label2.Padding = new Thickness(5, 0);
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label2.GridColumn = 1;
			label2.Border = new SolidBrush("#000000FF");

			var label3 = new Label();
			label3.Text = "↑ ou ↓";
			label3.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label3.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label3.TextColor = Color.Black;
			label3.BorderThickness = new Thickness(0, 0, 0, 1);
			label3.Padding = new Thickness(5, 0);
			label3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label3.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label3.GridColumn = 2;
			label3.Border = new SolidBrush("#000000FF");

			var label4 = new Label();
			label4.Text = "↔ ou ↕";
			label4.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label4.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label4.TextColor = Color.Black;
			label4.BorderThickness = new Thickness(0, 0, 0, 1);
			label4.Padding = new Thickness(5, 0);
			label4.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label4.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label4.GridColumn = 3;
			label4.Border = new SolidBrush("#000000FF");

			var label5 = new Label();
			label5.Text = "Suite";
			label5.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label5.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label5.TextColor = Color.Black;
			label5.BorderThickness = new Thickness(0, 0, 0, 1);
			label5.Padding = new Thickness(5, 0);
			label5.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label5.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label5.GridColumn = 4;
			label5.Border = new SolidBrush("#000000FF");

			movecolumnleft_button = new TextButton();
			movecolumnleft_button.Text = "◄";
			movecolumnleft_button.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			movecolumnleft_button.BorderThickness = new Thickness(0, 0, 0, 1);
			movecolumnleft_button.Padding = new Thickness(3, 0);
			movecolumnleft_button.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			movecolumnleft_button.GridColumn = 5;
			movecolumnleft_button.Border = new SolidBrush("#404040FF");
			movecolumnleft_button.Id = "movecolumnleft_button";

			movecolumnright_button = new TextButton();
			movecolumnright_button.Text = "►";
			movecolumnright_button.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			movecolumnright_button.BorderThickness = new Thickness(0, 0, 0, 1);
			movecolumnright_button.Padding = new Thickness(3, 0);
			movecolumnright_button.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			movecolumnright_button.GridColumn = 6;
			movecolumnright_button.Border = new SolidBrush("#404040FF");
			movecolumnright_button.Id = "movecolumnright_button";

			var label6 = new Label();
			label6.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label6.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label6.TextColor = Color.Black;
			label6.BorderThickness = new Thickness(0, 0, 0, 1);
			label6.Padding = new Thickness(5, 0);
			label6.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label6.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label6.GridColumn = 7;
			label6.Border = new SolidBrush("#000000FF");

			var label7 = new Label();
			label7.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label7.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label7.TextColor = Color.Black;
			label7.BorderThickness = new Thickness(0, 0, 0, 1);
			label7.Padding = new Thickness(5, 0);
			label7.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label7.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label7.GridColumn = 8;
			label7.Border = new SolidBrush("#000000FF");

			var label8 = new Label();
			label8.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label8.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label8.TextColor = Color.Black;
			label8.BorderThickness = new Thickness(0, 0, 0, 1);
			label8.Padding = new Thickness(5, 0);
			label8.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label8.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label8.GridColumn = 9;
			label8.Border = new SolidBrush("#000000FF");

			var label9 = new Label();
			label9.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label9.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label9.TextColor = Color.Black;
			label9.BorderThickness = new Thickness(0, 0, 0, 1);
			label9.Padding = new Thickness(5, 0);
			label9.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label9.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label9.GridColumn = 10;
			label9.Border = new SolidBrush("#000000FF");

			var label10 = new Label();
			label10.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label10.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label10.TextColor = Color.Black;
			label10.BorderThickness = new Thickness(0, 0, 0, 1);
			label10.Padding = new Thickness(5, 0);
			label10.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label10.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label10.GridColumn = 11;
			label10.Border = new SolidBrush("#000000FF");

			var label11 = new Label();
			label11.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label11.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label11.TextColor = Color.Black;
			label11.BorderThickness = new Thickness(0, 0, 0, 1);
			label11.Padding = new Thickness(5, 0);
			label11.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label11.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label11.GridColumn = 12;
			label11.Border = new SolidBrush("#000000FF");

			var label12 = new Label();
			label12.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label12.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label12.TextColor = Color.Black;
			label12.BorderThickness = new Thickness(0, 0, 0, 1);
			label12.Padding = new Thickness(5, 0);
			label12.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label12.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label12.GridColumn = 13;
			label12.Border = new SolidBrush("#000000FF");

			var label13 = new Label();
			label13.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label13.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label13.TextColor = Color.Black;
			label13.BorderThickness = new Thickness(0, 0, 0, 1);
			label13.Padding = new Thickness(5, 0);
			label13.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label13.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label13.GridColumn = 14;
			label13.Border = new SolidBrush("#000000FF");

			var label14 = new Label();
			label14.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label14.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label14.TextColor = Color.Black;
			label14.BorderThickness = new Thickness(0, 0, 0, 1);
			label14.Padding = new Thickness(5, 0);
			label14.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label14.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label14.GridColumn = 15;
			label14.Border = new SolidBrush("#000000FF");

			var label15 = new Label();
			label15.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label15.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label15.TextColor = Color.Black;
			label15.BorderThickness = new Thickness(0, 0, 0, 1);
			label15.Padding = new Thickness(5, 0);
			label15.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label15.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label15.GridColumn = 16;
			label15.Border = new SolidBrush("#000000FF");

			var label16 = new Label();
			label16.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label16.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			label16.TextColor = Color.Black;
			label16.BorderThickness = new Thickness(0, 0, 0, 1);
			label16.Padding = new Thickness(5, 0);
			label16.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label16.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label16.GridColumn = 17;
			label16.Border = new SolidBrush("#000000FF");

			var label17 = new Label();
			label17.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label17.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label17.GridColumn = 5;
			label17.GridRow = 1;
			label17.Background = new SolidBrush("#404040FF");

			var label18 = new Label();
			label18.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label18.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label18.GridColumn = 5;
			label18.GridRow = 2;
			label18.Background = new SolidBrush("#404040FF");

			var label19 = new Label();
			label19.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label19.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label19.GridColumn = 5;
			label19.GridRow = 3;
			label19.Background = new SolidBrush("#404040FF");

			var label20 = new Label();
			label20.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label20.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label20.GridColumn = 5;
			label20.GridRow = 4;
			label20.Background = new SolidBrush("#404040FF");

			var label21 = new Label();
			label21.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label21.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label21.GridColumn = 5;
			label21.GridRow = 5;
			label21.Background = new SolidBrush("#404040FF");

			var label22 = new Label();
			label22.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label22.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label22.GridColumn = 5;
			label22.GridRow = 6;
			label22.Background = new SolidBrush("#404040FF");

			var label23 = new Label();
			label23.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label23.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label23.GridColumn = 5;
			label23.GridRow = 7;
			label23.Background = new SolidBrush("#404040FF");

			var label24 = new Label();
			label24.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label24.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label24.GridColumn = 5;
			label24.GridRow = 8;
			label24.Background = new SolidBrush("#404040FF");

			var label25 = new Label();
			label25.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label25.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label25.GridColumn = 5;
			label25.GridRow = 9;
			label25.Background = new SolidBrush("#404040FF");

			var label26 = new Label();
			label26.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label26.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label26.GridColumn = 5;
			label26.GridRow = 10;
			label26.Background = new SolidBrush("#404040FF");

			var label27 = new Label();
			label27.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label27.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label27.GridColumn = 6;
			label27.GridRow = 1;
			label27.Background = new SolidBrush("#404040FF");

			var label28 = new Label();
			label28.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label28.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label28.GridColumn = 6;
			label28.GridRow = 2;
			label28.Background = new SolidBrush("#404040FF");

			var label29 = new Label();
			label29.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label29.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label29.GridColumn = 6;
			label29.GridRow = 3;
			label29.Background = new SolidBrush("#404040FF");

			var label30 = new Label();
			label30.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label30.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label30.GridColumn = 6;
			label30.GridRow = 4;
			label30.Background = new SolidBrush("#404040FF");

			var label31 = new Label();
			label31.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label31.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label31.GridColumn = 6;
			label31.GridRow = 5;
			label31.Background = new SolidBrush("#404040FF");

			var label32 = new Label();
			label32.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label32.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label32.GridColumn = 6;
			label32.GridRow = 6;
			label32.Background = new SolidBrush("#404040FF");

			var label33 = new Label();
			label33.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label33.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label33.GridColumn = 6;
			label33.GridRow = 7;
			label33.Background = new SolidBrush("#404040FF");

			var label34 = new Label();
			label34.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label34.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label34.GridColumn = 6;
			label34.GridRow = 8;
			label34.Background = new SolidBrush("#404040FF");

			var label35 = new Label();
			label35.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label35.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label35.GridColumn = 6;
			label35.GridRow = 9;
			label35.Background = new SolidBrush("#404040FF");

			var label36 = new Label();
			label36.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			label36.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			label36.GridColumn = 6;
			label36.GridRow = 10;
			label36.Background = new SolidBrush("#404040FF");

			gridfirstColumn_label = new Label();
			gridfirstColumn_label.Text = "Valentin";
			gridfirstColumn_label.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			gridfirstColumn_label.TextAlign = Myra.Graphics2D.UI.TextAlign.Center;
			gridfirstColumn_label.TextColor = Color.Black;
			gridfirstColumn_label.Padding = new Thickness(5, 0);
			gridfirstColumn_label.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			gridfirstColumn_label.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			gridfirstColumn_label.GridRow = 1;
			gridfirstColumn_label.Id = "gridfirstColumn_label";

			var label37 = new Label();
			label37.Text = "Michel";
			label37.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label37.TextColor = Color.Black;
			label37.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label37.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label37.GridRow = 2;

			var label38 = new Label();
			label38.Text = "Michel";
			label38.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label38.TextColor = Color.Black;
			label38.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label38.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label38.GridRow = 3;

			var label39 = new Label();
			label39.Text = "Michel";
			label39.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label39.TextColor = Color.Black;
			label39.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label39.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label39.GridRow = 4;

			var label40 = new Label();
			label40.Text = "Michel";
			label40.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label40.TextColor = Color.Black;
			label40.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label40.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label40.GridRow = 5;

			var label41 = new Label();
			label41.Text = "Michel";
			label41.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label41.TextColor = Color.Black;
			label41.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label41.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label41.GridRow = 6;

			var label42 = new Label();
			label42.Text = "Michel";
			label42.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label42.TextColor = Color.Black;
			label42.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label42.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label42.GridRow = 7;

			var label43 = new Label();
			label43.Text = "Michel";
			label43.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label43.TextColor = Color.Black;
			label43.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label43.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label43.GridRow = 8;

			var label44 = new Label();
			label44.Text = "Michel";
			label44.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label44.TextColor = Color.Black;
			label44.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label44.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label44.GridRow = 9;

			var label45 = new Label();
			label45.Text = "Michel";
			label45.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/consolas24.fnt");
			label45.TextColor = Color.Black;
			label45.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label45.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label45.GridRow = 10;

			
			ShowGridLines = true;
			GridLinesColor = Color.Black;
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			Background = new SolidBrush("#FFFFFFFF");
			Id = "score_grid";
			Widgets.Add(gridcontent_label);
			Widgets.Add(gridfirstcolumn_label);
			Widgets.Add(gridfirstrowmovablecolumns_label);
			Widgets.Add(graycell_label);
			Widgets.Add(label1);
			Widgets.Add(label2);
			Widgets.Add(label3);
			Widgets.Add(label4);
			Widgets.Add(label5);
			Widgets.Add(movecolumnleft_button);
			Widgets.Add(movecolumnright_button);
			Widgets.Add(label6);
			Widgets.Add(label7);
			Widgets.Add(label8);
			Widgets.Add(label9);
			Widgets.Add(label10);
			Widgets.Add(label11);
			Widgets.Add(label12);
			Widgets.Add(label13);
			Widgets.Add(label14);
			Widgets.Add(label15);
			Widgets.Add(label16);
			Widgets.Add(label17);
			Widgets.Add(label18);
			Widgets.Add(label19);
			Widgets.Add(label20);
			Widgets.Add(label21);
			Widgets.Add(label22);
			Widgets.Add(label23);
			Widgets.Add(label24);
			Widgets.Add(label25);
			Widgets.Add(label26);
			Widgets.Add(label27);
			Widgets.Add(label28);
			Widgets.Add(label29);
			Widgets.Add(label30);
			Widgets.Add(label31);
			Widgets.Add(label32);
			Widgets.Add(label33);
			Widgets.Add(label34);
			Widgets.Add(label35);
			Widgets.Add(label36);
			Widgets.Add(gridfirstColumn_label);
			Widgets.Add(label37);
			Widgets.Add(label38);
			Widgets.Add(label39);
			Widgets.Add(label40);
			Widgets.Add(label41);
			Widgets.Add(label42);
			Widgets.Add(label43);
			Widgets.Add(label44);
			Widgets.Add(label45);
		}

		
		public Label gridcontent_label;
		public Label gridfirstcolumn_label;
		public Label gridfirstrowmovablecolumns_label;
		public Label graycell_label;
		public TextButton movecolumnleft_button;
		public TextButton movecolumnright_button;
		public Label gridfirstColumn_label;
	}
}