/* Generated by MyraPad at 07/11/2020 14:09:47 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace Rivière.Screen.UI
{
	partial class SplashScreenUI: Panel
	{
		private void BuildUI()
		{
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("images/splash_screen_bg.jpg");

			var label1 = new Label();
			label1.Text = "RIVIERE";
			label1.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans72.fnt");
			label1.TextColor = Color.Black;
			label1.Top = -75;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label1.Background = new SolidBrush("#00000000");

			var label2 = new Label();
			label2.Text = "Le jeu";
			label2.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans48.fnt");
			label2.TextColor = Color.Black;
			label2.Top = -10;
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			start_button = new TextButton("transparent-bg");
			start_button.Text = "Cliquez pour demarrer";
			start_button.TextColor = Color.Black;
			start_button.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("fonts/comicSans48.fnt");
			start_button.Visible = false;
			start_button.Top = 130;
			start_button.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			start_button.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			start_button.Id = "start_button";

			
			Widgets.Add(image1);
			Widgets.Add(label1);
			Widgets.Add(label2);
			Widgets.Add(start_button);
		}

		
		public TextButton start_button;
	}
}